---

- name: Add settings.local.php file.
  copy:
    src: "{{ docroot }}/sites/example.settings.local.php"
    dest: "{{ docroot }}/sites/default/settings.local.php"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    remote_src: yes
  become: yes
  tags: d8_dev_setup_settings_local

- name: Enable settings.local.php file.
  blockinfile:
    dest: "{{ docroot }}/sites/default/settings.php"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    marker: "# {mark} ANSIBLE MANAGED SETTINGS LOCAL"
    block: |
      if (file_exists(__DIR__ . '/settings.local.php')) {
        include __DIR__ . '/settings.local.php';
      }
  become: yes
  notify: clear drupal 8 cache
  tags: d8_dev_setup_settings_local_enable

- name: Set up settings.local.php file.
  blockinfile:
    dest: "{{ docroot }}/sites/default/settings.local.php"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    marker: "# {mark} ANSIBLE MANAGED CACHE"
    block: |
      $settings['cache']['bins']['render'] = 'cache.backend.null';
      $settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
      $settings['cache']['bins']['page'] = 'cache.backend.null';
  become: yes
  notify: clear drupal 8 cache
  tags: d8_dev_setup_settings_local_setup

- name: Add additional lines to settings.local.php.
  lineinfile:
    dest: "{{ docroot }}/sites/default/settings.local.php"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    state: present
    line: "{{ item }}"
  become: yes
  with_items: "{{ settings_local_additional_lines }}"
  when: settings_local_additional_lines is defined
  notify: clear drupal 8 cache
  tags: d8_dev_setup_settings_local_additional_lines

- name: Enable twig debugging.
  blockinfile:
    dest: "{{ docroot }}/sites/development.services.yml"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    marker: "# {mark} ANSIBLE MANAGED TWIG DEBUGGING"
    block: |
      # This line is here so the line below gets indented properly.
        twig.config:
          debug: true
          auto_reload: true
          cache: false
    insertafter: "parameters:"
  become: yes
  notify: clear drupal 8 cache
  tags: d8_dev_setup_twig_debug

- name: Protect settings.local.php file.
  file:
    path: "{{ docroot }}/sites/default/settings.local.php"
    mode: 0644
  become: yes
  tags: d8_dev_setup_protect_files

- name: Enable developer modules.
  shell: drush en {{ item }} -y
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ d8_dev_modules }}"
  tags: d8_dev_setup_modules

# Setting this in the DB and not in settings.local.php since it's handy to change this in the UI sometimes.
- name: Set up devel module.
  shell: drush config-set devel.settings devel_dumper {{ devel_dumper }} -y
  args:
    chdir: "{{ docroot }}"
  tags: d8_dev_setup_devel_dumper
