---

- name: Enable modules.
  shell: drush en {{ item }} -y
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ post_install_modules|default([]) }}"
  when: post_install_modules is defined
  tags: post_install_modules
  
- name: Run migrations.
  shell: drush mi --group={{ item }}
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ migrate_groups|default([]) }}"
  when: migrate_groups is defined
  tags: post_install_migrate

- name: Enable modules post-migration.
  shell: drush en {{ item }} -y
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ post_migrate_modules|default([]) }}"
  when: post_migrate_modules is defined
  tags: post_migrate_modules

- name: Build search index.
  shell: drush search-index
  args:
    chdir: "{{ docroot }}"
  when: build_search_index
  tags: post_install_modules

- name: Generate commerce orders for additional users.
  shell: drush --user={{ item.name }} commerce-order-add {{ item.commerce_order }} && drush --user={{ item.name }} commerce-order-pay
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ additional_users }}"
  when: additional_users is defined and item.commerce_order is defined
  tags: post_install_commerce_orders

- name: Run any additional commands.
  shell: "{{ item }}"
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ post_install_add_commands|default([]) }}"
  when: post_install_add_commands is defined
  tags: post_install_add_commands
