---

- name: Enable modules.
  shell: drush en {{ item }} -y
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ post_install_modules }}"
  when: post_install_modules is defined
  tags: post_install_modules
  
- name: Run migrations.
  command: drush -r {{ docroot }} mi --group={{ item }} --user=1
  with_items: "{{ migrate_groups }}"
  when: migrate_groups is defined
  tags: post_install_migrate

- name: Build search index.
  shell: drush search-index
  args:
    chdir: "{{ docroot }}"
  when: build_search_index
  tags: post_install_modules

- name: Generate commerce orders for additional users.
  shell: drush --user={{ item.name }} commerce-order-add {{ item.commerce_order }} && drush --user={{ item.name }} commerce-order-pay
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ additional_users }}"
  when: item.commerce_order is defined
  tags: post_install_commerce_orders