---

- name: Create additional users.
  shell: drush user-create {{ item.name }} --password="{{ item.pass }}" --mail="{{ item.email }}" -y
  args:
    chdir: "{{ docroot }}"
  with_items: "{{ additional_users }}"
  when: additional_users is defined
  tags: users_create_users

- name: Assign roles to additional users.
  shell: drush user-add-role "{{ item.1 }}" {{ item.0.name }} -y
  args:
    chdir: "{{ docroot }}"
  with_subelements:
    - "{{ additional_users }}"
    - roles
  when: additional_users is defined
  tags: users_add_roles
