---

- name: Remove project directory.
  file:
    path: "{{ project_dir }}"
    state: absent
  become: yes

- name: Create new Drupal 8 project.
  shell: "{{ composer_path | default('/usr/local/bin/composer') }} create-project drupal-composer/drupal-project:8.x-dev {{ project_dir }} --stability dev --no-interaction"
