---

- name: Remove settings files.
  file:
    path: "{{ docroot }}/sites/default/{{ item }}"
    state: absent
  with_items:
    - settings.php
    - settings.local.php
  tags: d8_reset_settings_files

- name: Create new settings file.
  copy:
    src: "{{ docroot }}/sites/default/default.settings.php"
    dest: "{{ docroot }}/sites/default/settings.php"
    mode: 0777
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
  tags: d8_reset_settings_files

- name: Remove twig debugging.
  blockinfile:
    dest: "{{ docroot }}/sites/development.services.yml"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    marker: "# {mark} ANSIBLE MANAGED TWIG DEBUGGING"
    block: |
      # This line is here so the line below gets indented properly.
        twig.config:
          debug: true
          auto_reload: true
          cache: false
    insertafter: "parameters:"
    state: absent
  become: yes
  #notify: clear drupal 8 cache
  tags: d8_reset_remove_twig_debug

- name: Remove files directory.
  file:
    path: "{{ files_dir }}"
    state: absent
  tags: d8_reset_files_dir

- name: Create new files directory.
  file:
    path: "{{ files_dir }}"
    state: directory
    mode: 0777
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
  tags: d8_reset_files_dir

- name: Remove private files directory.
  file:
    path: "{{ private_files_dir_path }}"
    state: absent
  when: private_files_dir_path is defined
  tags: d8_reset_files_dir

- name: Create new private files directory.
  file:
    path: "{{ private_files_dir_path }}"
    state: directory
    mode: 0777
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
  when: private_files_dir_path is defined
  tags: d8_reset_files_dir

- name: Remove config directory.
  file:
    path: "{{ config_dir }}"
    state: absent
  tags: d8_reset_config_dir

- name: Create new config directory.
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: 0777
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
  tags: d8_reset_config_dir
