---

- name: Add additional database info to Drupal 8 settings.php.
  blockinfile:
    dest: "{{ docroot }}/sites/default/settings.php"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    marker: "# {mark} ANSIBLE MANAGED ADDITIONAL DATABASE"
    block: |
      $databases['{{ d8_legacy_db_group }}']['default'] = array (
        'database' => '{{ d8_legacy_db_name }}',
        'username' => '{{ d8_legacy_db_user }}',
        'password' => '{{ d8_legacy_db_pass }}',
        'prefix' => '',
        'host' => 'localhost',
        'port' => '',
        'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
        'driver' => 'mysql',
      );
  become: yes
  when: d8_legacy_db_name is defined
  notify: clear drupal 8 cache
